### DISCUSSION TITLE
please show in docker config

### DISCUSSION THREAD

**Discussion by vahidalvandi** [spatie/laravel-varnish#66] [Q&A]
hi , thank you .

pplease show me how to config default.vcl and config.php in docker compose

i configure docker but have error in run 

```
version: "3.9"
services:
  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./infra/docker/varnish/default.vcl:/etc/varnish/default.vcl"
    ports:
      - "8080:8080"
```

return error logs for **default.vcl**

```
if (beresp.http.X-Cacheable ~ "1") {
    unset beresp.http.set-cookie;
}
```

**varnish  | Error:
varnish  | Message from VCC-compiler:
varnish  | VCL version declaration missing
varnish  | Update your VCL to Version 4 syntax, and add
varnish  | 	vcl 4.1;
varnish  | on the first line of the VCL files.
varnish  | ('/etc/varnish/default.vcl' Line 1 Pos 1)
varnish  | if (beresp.http.X-Cacheable ~ "1") {
varnish  | ##----------------------------------
varnish  | 
varnish  | Running VCC-compiler failed, exited with 2
varnish  | VCL compilation failed
varnish  | Error:
varnish  | Message from VCC-compiler:
varnish  | VCL version declaration missing
varnish  | Update your VCL to Version 4 syntax, and add
varnish  | 	vcl 4.1;
varnish  | on the first line of the VCL files.
varnish  | ('/etc/varnish/default.vcl' Line 1 Pos 1)
varnish  | if (beresp.http.X-Cacheable ~ "1") {**
